# **************************************************************************** #
#                                                           LE - /             #
#                                                               /              #
#    .gitlab-ci.yml                                   .::    .:/ .      .::    #
#                                                  +:+:+   +:    +:  +:+:+     #
#    By: eschnell <eschnell@student.le-101.fr>      +:+   +:    +:    +:+      #
#                                                  #+#   #+    #+    #+#       #
#    Created: 2018/10/21 11:42:57 by eschnell     #+#   ##    ##    #+#        #
#    Updated: 2018/11/17 17:01:28 by eschnell    ###    #+. /#+    ###.fr      #
#                                                          /                   #
#                                                         /                    #
# **************************************************************************** #

variables:
  OMNIBUS_BRANCH: 'master'

image: gcc

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - fillit
    expire_in: 1 week

.tests:
  stage: find
  script:
    - find . -name "fillit"
  stage: test_algo
  script:
    - ./fillit examples/valid_15

uni:
  extends: .tests
  stage: test_unicode
  script:
    - ./fillit -u examples/valid_15

#deploy:
#  stage: deploy
#  image: curl
#  script:
#    - "curl -X POST -F token=4a9397dda56ea21240452825775e85 -F ref=master https://gitlab.com/api/v4/projects/9131627/trigger/pipeline"
