# **************************************************************************** #
#                                                           LE - /             #
#                                                               /              #
#    .gitlab-ci.yml                                   .::    .:/ .      .::    #
#                                                  +:+:+   +:    +:  +:+:+     #
#    By: eschnell <eschnell@student.le-101.fr>      +:+   +:    +:    +:+      #
#                                                  #+#   #+    #+    #+#       #
#    Created: 2018/10/21 11:42:57 by eschnell     #+#   ##    ##    #+#        #
#    Updated: 2018/11/17 17:14:54 by eschnell    ###    #+. /#+    ###.fr      #
#                                                          /                   #
#                                                         /                    #
# **************************************************************************** #

variables:
  OMNIBUS_BRANCH: 'master'

image: gcc

build:
  stage: build
  script: make
  artifacts:
    paths:
      - fillit
    expire_in: 1 week

test_algo:
  stage: find
  script:
    - find . -name "fillit"
  stage: test
  script: ./fillit examples/valid_15

test_uni:
  extends: test_algo
  stage: test
  script: ./fillit -u examples/valid_15

test_palette:
  extends: test_uni
  stage: test
  script: ./fillit -p

#deploy:
#  stage: deploy
#  image: curl
#  script:
#    - "curl -X POST -F token=4a9397dda56ea21240452825775e85 -F ref=master https://gitlab.com/api/v4/projects/9131627/trigger/pipeline"
